Models/Accesorio.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repaso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accesorio
    {
        public int Id { get; set; }
        public int idvehiculo { get; set; }
        public string nombre { get; set; }
    
        public virtual vehiculo vehiculo { get; set; }
    }
}

Controllers/AccesorioController.cs
using Repaso.Dato;
using Repaso.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Repaso.Controllers
{
    public class AccesorioController : Controller
    {
        AccesorioAdmin admin = new AccesorioAdmin();
        private IEnumerable<SelectListItem> vehiculos;
        public void LlenarCombo()
        {
            vehiculos = new VehiculoAdmin().Consultar().ToList().Select(p => new SelectListItem { Value = p.Id.ToString(), Text = p.marca + " " + p.precio }); ;

        }
        // GET: Accesorio
        public ActionResult Index()
        {

            return View(admin.Consultar());
        }
        public ActionResult Guardar() {
            LlenarCombo();
            VehiculoAccesorioModel modelo = new VehiculoAccesorioModel() {
                ListadoVehiculos = vehiculos
            };
            ViewBag.mensaje = "";
            return View(modelo);
        }
        public ActionResult Nuevo(VehiculoAccesorioModel modelo) {
            //Accesorio modeloAux = modelo.accesorio;
            Accesorio modeloAux = new Accesorio() {
                idvehiculo = modelo.accesorio.idvehiculo,
                nombre = modelo.accesorio.nombre
            };
            admin.Guardar(modeloAux);
            LlenarCombo();
            //modelo.ListadoVehiculos = vehiculos;
            modelo = new VehiculoAccesorioModel() {
                ListadoVehiculos = vehiculos
            };
            ViewBag.mensaje = "Accesorio Guardado";
            return View("Guardar", modelo);
        }
        public ActionResult Modificar(int id=0) {
            LlenarCombo();
            VehiculoAccesorioModel modelo = new VehiculoAccesorioModel()
            {
                ListadoVehiculos = vehiculos,
                accesorio=admin.Consultar(id)
            };
            ViewBag.mensaje = "";
            return View(modelo);
        }
        public ActionResult Actualizar(VehiculoAccesorioModel modelo) {
            Accesorio modeloAux = new Accesorio()
            {
                idvehiculo = modelo.accesorio.idvehiculo,
                nombre = modelo.accesorio.nombre,
                Id=modelo.accesorio.Id
            };
            admin.Modificar(modeloAux);
            LlenarCombo();
            modelo.ListadoVehiculos = vehiculos;            
            ViewBag.mensaje = "Accesorio Modificado";
            return View("Modificar", modelo);
        }

    }
}

Views/Accesorio/Guardar.cshtml
@model Repaso.Models.VehiculoAccesorioModel

@{
    ViewBag.Title = "Guardar";
}

<h2>Guardar</h2>


@using (Html.BeginForm("Nuevo", "Accesorio", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Accesorio</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.accesorio.idvehiculo, "idvehiculo", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.accesorio.idvehiculo, Model.ListadoVehiculos)
            @Html.ValidationMessageFor(model => model.accesorio.idvehiculo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.accesorio.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.accesorio.nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.accesorio.nombre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Guardar" class="btn btn-default" />
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <font color="green">@ViewBag.mensaje</font>
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Accesorio/Index.cshtml
@model IEnumerable<Repaso.Models.Accesorio>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Crear Nuevo", "Guardar")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nombre)
        </th>
        <th>
         
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.nombre)
        </td>
        <td>
          
        </td>
        <td>
            @Html.ActionLink("Editar", "Modificar", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

Views/Accesorio/Modificar.cshtml
@model Repaso.Models.VehiculoAccesorioModel

@{
    ViewBag.Title = "Modificar";
}

<h2>Modificar</h2>

@using (Html.BeginForm("Actualizar", "Accesorio", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Accesorio</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.accesorio.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.accesorio.idvehiculo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.accesorio.idvehiculo, Model.ListadoVehiculos)
                @Html.ValidationMessageFor(model => model.accesorio.idvehiculo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.accesorio.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.accesorio.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.accesorio.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Modificar" class="btn btn-default" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <font color="green">@ViewBag.mensaje</font>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}