Models/vehiculo.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repaso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vehiculo()
        {
            this.Accesorio = new HashSet<Accesorio>();
        }
    
        public int Id { get; set; }
        public string marca { get; set; }
        public int precio { get; set; }
        public string foto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accesorio> Accesorio { get; set; }
    }
}

Controllers/VehiculoController.cs
using Repaso.Dato;
using Repaso.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Repaso.Controllers
{
    public class VehiculoController : Controller
    {
        VehiculoAdmin admin = new VehiculoAdmin();
        // GET: Vehiculo
        public ActionResult Index()
        {
            IEnumerable<vehiculo> lista = admin.Consultar();
            ViewBag.mensaje = "";
            return View(lista);
        }
        public ActionResult Guardar() {
            ViewBag.mensaje = "";
            return View();
        }

        public ActionResult Nuevo(vehiculo modelo) {
            admin.Guardar(modelo);
            ViewBag.mensaje = "Vehiculo Guardado";
            return View("Guardar",modelo);
        }

        public ActionResult Detalle(int id=0) {
            vehiculo modelo = admin.Consultar(id);
            ViewBag.mensaje = "";
            return View(modelo);
        }
        public ActionResult Modificar(int id = 0) {
            vehiculo modelo = admin.Consultar(id);
            return View(modelo);
        }

        public ActionResult Actualizar(vehiculo modelo) {
            admin.Modificar(modelo);
            ViewBag.mensaje = "Vehiculo Modificado";
            return View("Modificar", modelo);
        }

        public ActionResult Eliminar(int id = 0) {
            vehiculo modelo = new vehiculo() { 
            Id=id
            };
            admin.Eliminar(modelo);
            IEnumerable<vehiculo> lista = admin.Consultar();
            ViewBag.mensaje = "Vehiculo Eliminado";
            return View("Index",lista);
        }

        public ActionResult Consulta() {
            IEnumerable<Sp_ConsultarVehiculo2_Result> lista = admin.ConsultarSp();
            return View(lista);
        }
    }
}

Views/Vehiculo/Consulta.cshtml
@model IEnumerable<Repaso.Models.Sp_ConsultarVehiculo2_Result>

@{
    ViewBag.Title = "Consulta";
}

<h2>Consulta</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.marca)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.precio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.foto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Id_Accesorio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.idvehiculo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.marca)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.precio)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.foto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Id_Accesorio)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.idvehiculo)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

Views/Vehiculo/Detalle.cshtml
@model Repaso.Models.vehiculo

@{
    ViewBag.Title = "Detalle";
}

<h2>Detalle</h2>

<div>
    <h4>vehiculo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.marca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.marca)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.precio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.foto)
        </dt>

        <dd>
            <img src="@Html.DisplayFor(model => model.foto)" width="400" />
            
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Vehiculo/Guardar.cshtml
@model Repaso.Models.vehiculo

@{
    ViewBag.Title = "Guardar";
}

<h2>Guardar</h2>


@using (Html.BeginForm("Nuevo", "Vehiculo", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>vehiculo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.marca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.marca, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.marca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.foto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.foto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.foto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <font color="green">@ViewBag.mensaje</font>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Vehiculo/Index.cshtml
@model IEnumerable<Repaso.Models.vehiculo>

@{
    ViewBag.Title = "Index";

}

<h2>Index</h2>

<p>
    @Html.ActionLink("Crear Nuevo", "Guardar")
</p>
<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <font color="green">@ViewBag.mensaje</font>
    </div>
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.marca)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.precio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.foto)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.marca)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.precio)
            </td>
            <td>
                <img src="@Html.DisplayFor(modelItem => item.foto)" width="200px" />

            </td>
            <td>
                @Html.ActionLink("Editar", "Modificar", new { id = item.Id }) |
                @Html.ActionLink("Ver", "Detalle", new { id = item.Id }) |
                @Html.ActionLink("Borrar", "Eliminar", new { id = item.Id })
            </td>
        </tr>
    }

</table>

Views/Vehiculo/Modificar.cshtml
@model Repaso.Models.vehiculo

@{
    ViewBag.Title = "Modificar";
}

<h2>Modificar</h2>


@using (Html.BeginForm("Actualizar", "Vehiculo", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>vehiculo</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.marca, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.marca, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.marca, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.precio, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.precio, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.precio, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.foto, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.foto, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.foto, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Modificar" class="btn btn-default" />
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <font color="green">@ViewBag.mensaje</font>
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}